FROM docker.emias.ru/dockerhub/library/python:3.10-slim as requirements-stage
WORKDIR /tmp
COPY ./packages /tmp/packages
COPY ./requirements.txt /tmp/
RUN pip install --no-index --find-links=/tmp/packages -r /tmp/requirements.txt

FROM docker.emias.ru/dockerhub/library/python:3.10-slim
WORKDIR /code
COPY --from=requirements-stage /tmp/packages /code/packages
COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt
RUN pip install --no-index --find-links=/code/packages -r /code/requirements.txt
COPY ./alembic /code/alembic
COPY ./alembic.ini /code
COPY ./run.py /code


