services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_nginx
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && export PYTHONPATH=$PYTHONPATH:$(pwd) && python run.py"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./
        target: /code

    networks:
      - my_admin

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env_nginx
    ports:
      - "8124:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_admin

  redis:
    image: redis:latest
    volumes:
      - redis_data:/usr/local/etc/redis
    env_file: .env_nginx
    ports:
      - "6379:6379"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - my_admin

networks:
  my_admin:
    driver: bridge
volumes:
  postgres_data:
  redis_data:
